import { Toaster } from "sonner";
import "./globals.css";

export const metadata = {
  title: "Golden Bulls - Admin",
  description: "Generated by Golden Bulls - Admin",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster
          position="bottom-right"
          richColors
          theme="dark"
          toastOptions={{
            style: {
              background: "#1a1a1a",
              color: "#fff",
              border: "1px solid #333",
              borderRadius: "8px",
            },
          }}
        />
      </body>
    </html>
  );
}
